gh-notify fork that marks messages as done (along with marking as read)

diff --git a/gh-notify b/gh-notify
--- a/gh-notify
+++ b/gh-notify
@@ -31,9 +31,10 @@ GH_NOTIFY_PER_PAGE_LIMIT=50
 : "${GH_NOTIFY_MARK_ALL_READ_KEY:=ctrl-a}"
 : "${GH_NOTIFY_OPEN_BROWSER_KEY:=ctrl-b}"
 : "${GH_NOTIFY_VIEW_DIFF_KEY:=ctrl-d}"
-: "${GH_NOTIFY_VIEW_PATCH_KEY:=ctrl-p}"
+: "${GH_NOTIFY_VIEW_PATCH_KEY:=ctrl-f}"
 : "${GH_NOTIFY_RELOAD_KEY:=ctrl-r}"
 : "${GH_NOTIFY_MARK_READ_KEY:=ctrl-t}"
+: "${GH_NOTIFY_MARK_DONE_KEY:=ctrl-w}"
 : "${GH_NOTIFY_COMMENT_KEY:=ctrl-x}"
 : "${GH_NOTIFY_TOGGLE_KEY:=ctrl-y}"
 : "${GH_NOTIFY_RESIZE_PREVIEW_KEY:=btab}"
@@ -139,7 +140,7 @@ ${WHITE_BOLD}Usage${NC}
 
 ${WHITE_BOLD}Flags${NC}
   ${GREEN}<none>${NC}  show all unread notifications
-  ${GREEN}-a    ${NC}  show all (read/ unread) notifications
+  ${GREEN}-a    ${NC}  show all (read/unread) notifications
   ${GREEN}-e    ${NC}  exclude notifications matching a string (REGEX support)
   ${GREEN}-f    ${NC}  filter notifications matching a string (REGEX support)
   ${GREEN}-h    ${NC}  show the help page
@@ -151,29 +152,31 @@ ${WHITE_BOLD}Flags${NC}
   ${GREEN}-w    ${NC}  display the preview window in interactive mode
 
 ${WHITE_BOLD}Key Bindings fzf${NC}
-  ${GREEN}${GH_NOTIFY_TOGGLE_HELP_KEY}        ${NC}  toggle help
-  ${GREEN}${GH_NOTIFY_VIEW_KEY}    ${NC}  view the selected notification in the 'less' pager
-  ${GREEN}${GH_NOTIFY_TOGGLE_PREVIEW_KEY}      ${NC}  toggle notification preview
-  ${GREEN}${GH_NOTIFY_RESIZE_PREVIEW_KEY}${NC}       resize the preview window
-  ${GREEN}shift+↑↓ ${NC}  scroll the preview up/ down
-  ${GREEN}${GH_NOTIFY_MARK_ALL_READ_KEY}   ${NC}  mark all displayed notifications as read and reload
-  ${GREEN}${GH_NOTIFY_OPEN_BROWSER_KEY}   ${NC}  browser
-  ${GREEN}${GH_NOTIFY_VIEW_DIFF_KEY}   ${NC}  view diff
-  ${GREEN}${GH_NOTIFY_VIEW_PATCH_KEY}   ${NC}  view diff in patch format
-  ${GREEN}${GH_NOTIFY_RELOAD_KEY}   ${NC}  reload
-  ${GREEN}${GH_NOTIFY_MARK_READ_KEY}   ${NC}  mark the selected notification as read and reload
-  ${GREEN}${GH_NOTIFY_COMMENT_KEY}   ${NC}  write a comment with the editor and quit
-  ${GREEN}${GH_NOTIFY_TOGGLE_KEY}   ${NC}  toggle the selected notification
-  ${GREEN}esc      ${NC}  quit
+  ${GREEN}${GH_NOTIFY_TOGGLE_HELP_KEY}${NC}                     toggle help
+  ${GREEN}↑↓,ctrl+j/k,ctrl+n/p${NC}  move the pointer up/down
+  ${GREEN}${GH_NOTIFY_VIEW_KEY}${NC}                 show issue/PR for notification at pointer
+  ${GREEN}tab${NC}                   show/hide preview of issue/PR for notification at pointer
+  ${GREEN}shift+tab${NC}             resize the preview window
+  ${GREEN}shift+↑↓${NC}              scroll the preview-window contents up/down
+  ${GREEN}${GH_NOTIFY_MARK_ALL_READ_KEY}${NC}                mark all displayed notifications as read, and reload
+  ${GREEN}${GH_NOTIFY_OPEN_BROWSER_KEY}${NC}                open in browser
+  ${GREEN}${GH_NOTIFY_VIEW_DIFF_KEY}${NC} / ${GREEN}${GH_NOTIFY_VIEW_PATCH_KEY}${NC}       view diff / view diff in patch format
+  ${GREEN}${GH_NOTIFY_RELOAD_KEY}${NC}                reload
+  ${GREEN}${GH_NOTIFY_MARK_READ_KEY}${NC}                mark selected notification as read, and reload
+  ${GREEN}${GH_NOTIFY_MARK_DONE_KEY}${NC}                mark selected notification as read+done, and reload
+  ${GREEN}${GH_NOTIFY_COMMENT_KEY}${NC}                write a comment with the editor and quit
+  ${GREEN}${GH_NOTIFY_TOGGLE_KEY}${NC}                toggle the selected notification
+  ${GREEN}esc${NC}                   quit
 
 ${WHITE_BOLD}Table Format${NC}
-  ${GREEN}unread symbol${NC}  indicates unread status
-  ${GREEN}time         ${NC}  time of last read for unread; otherwise, time of last update
-  ${GREEN}repo         ${NC}  related repository
-  ${GREEN}type         ${NC}  notification type
-  ${GREEN}number       ${NC}  associated number
-  ${GREEN}reason       ${NC}  trigger reason
-  ${GREEN}title        ${NC}  notification title
+  \033[38;5;160m▶\033[0m                              pointer
+  \u001b[35m\u25cf\u001b[0m                              indicates unread status
+  ${GREEN}0h ago / 01 Foo 00:00${NC}          time of last read for unread; otherwise, time of last update
+  ${GREEN}foo/bar${NC}                        repository that generated the notification
+  ${GREEN}Issue/PullRequest/Discussion${NC}   notification type
+  ${GREEN}#0000${NC}                          issue/PR/discussion number
+  ${GREEN}subscribed, etc.${NC}               trigger reason
+  ${GREEN}Foo the bar baz${NC}                issue/PR/discussion title
 
 ${WHITE_BOLD}Example${NC}
     ${DARK_GRAY}# Display the last 20 notifications${NC}
@@ -539,6 +542,35 @@ mark_individual_read() {
     fi
 }
 
+mark_individual_done() {
+    local thread_id thread_state
+    declare -a array_threads=()
+    while IFS=' ' read -r _ thread_id thread_state _; do
+        if [[ $thread_state == "UNREAD" ]]; then
+            array_threads+=("$thread_id")
+        fi
+    done <"$1"
+
+    if [[ ${#array_threads[@]} -eq 1 ]]; then
+        gh_rest_api --silent --method DELETE "notifications/threads/${array_threads[0]}" ||
+            die "Failed to mark notifications as done."
+    elif [[ ${#array_threads[@]} -gt 1 ]]; then
+        # If there is a large number of threads to be processed, the number of background jobs can
+        # put pressure on the PC. Additionally, too many requests in short succession can trigger a
+        # rate limit by GitHub. Therefore, we process the threads in batches of 30, with a short
+        # delay of 0.3 seconds between each batch. This approach worked well in my tests with 200
+        # notifications.
+        for ((i = 0; i < ${#array_threads[@]}; i += 30)); do
+            for j in "${array_threads[@]:i:30}"; do
+                # Running commands in the background of a script can cause it to hang, especially if
+                # the command outputs to stdout: https://tldp.org/LDP/abs/html/x9644.html#WAITHANG
+                gh_rest_api --silent --method DELETE "notifications/threads/${j}" &>/dev/null &
+            done
+            command sleep 0.3
+        done
+    fi
+}
+
 select_notif() {
     local output expected_key selected_line repo_full_name type num
     # Export functions to child processes. 'fzf' executes commands with $SHELL -c; to ensure
@@ -546,7 +578,7 @@ select_notif() {
     export -f print_help_text print_notifs get_notifs
     export -f process_page process_discussion process_url gh_rest_api
     export -f highlight_output open_in_browser view_notification view_in_pager
-    export -f mark_all_read mark_individual_read
+    export -f mark_all_read mark_individual_read mark_individual_done
     # The 'die' function is not exported because 'fzf' warns you about the error in
     # a failed 'print_notifs' call, but does not display the message.
 
@@ -562,6 +594,7 @@ select_notif() {
             --bind "${GH_NOTIFY_VIEW_PATCH_KEY}:toggle-preview+change-preview:if command grep -q PullRequest <<<{10}; then command gh pr diff {11} --patch --repo {5} | highlight_output; else view_notification {}; fi" \
             --bind "${GH_NOTIFY_RELOAD_KEY}:reload:print_notifs || true" \
             --bind "${GH_NOTIFY_MARK_READ_KEY}:execute-silent(mark_individual_read {+f})+reload:print_notifs || true" \
+            --bind "${GH_NOTIFY_MARK_DONE_KEY}:execute-silent(mark_individual_read {+f}; mark_individual_done {+f})+reload:print_notifs || true" \
             --bind "${GH_NOTIFY_TOGGLE_KEY}:toggle+down" \
             --bind "${GH_NOTIFY_VIEW_KEY}:execute:view_in_pager {}" \
             --bind "${GH_NOTIFY_TOGGLE_PREVIEW_KEY}:toggle-preview+change-preview:view_notification {}" \
